package Operations_package;

import static Operations_package.ReceiptPrinter.printComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Akash Pawar
 */
public class ReportPrinter extends javax.swing.JFrame {

    /**
     * Creates new form ReportPrinter
     */
    public ReportPrinter(String action, String from, String to, String a1, String a2, String a3, String a4, String a5, 
            String b1, String b2, String b3, String b4, String b5, String p1, String p2, String p3, String p4, String p5) {
        this.setUndecorated(true);
        initComponents();
        
        if(action.equals("most")){
            Report_lbl_action.setText("Top 5 most sold");
        }
        if(action.equals("least")){
            Report_lbl_action.setText("Top 5 least sold");
        }
        Report_lbl_fromDate.setText(from);
        Report_lbl_toDate.setText(to);
        Report_lbl_pid1.setText(a1);
        Report_lbl_pid2.setText(a2);
        Report_lbl_pid3.setText(a3);
        Report_lbl_pid4.setText(a4);
        Report_lbl_pid5.setText(a5);
        Report_lbl_qty1.setText(b1);
        Report_lbl_qty2.setText(b2);
        Report_lbl_qty3.setText(b3);
        Report_lbl_qty4.setText(b4);
        Report_lbl_qty5.setText(b5);
        Report_lbl_PName1.setText(p1);
        Report_lbl_PName2.setText(p2);
        Report_lbl_PName3.setText(p3);
        Report_lbl_PName4.setText(p4);
        Report_lbl_PName5.setText(p5);
        
        this.setLocationRelativeTo(null);   //jframe to center
        this.setResizable(false); 
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportPanel = new javax.swing.JPanel();
        base_lbl_title = new javax.swing.JLabel();
        base_lbl_subheading = new javax.swing.JLabel();
        base_lbl_emoticon = new javax.swing.JLabel();
        base_lbl_Date = new javax.swing.JLabel();
        base_logoPanel = new javax.swing.JPanel();
        base_logoPanel_lbl_flowerImage = new javax.swing.JLabel();
        lbl_address1 = new javax.swing.JLabel();
        lbl_address2 = new javax.swing.JLabel();
        lbl_address3 = new javax.swing.JLabel();
        lbl_dateSpanning = new javax.swing.JLabel();
        lbl_dateFrom = new javax.swing.JLabel();
        lbl_dateTo = new javax.swing.JLabel();
        Report_lbl_fromDate = new javax.swing.JLabel();
        Report_lbl_toDate = new javax.swing.JLabel();
        Report_lbl_action = new javax.swing.JLabel();
        lbl_PID = new javax.swing.JLabel();
        lbl_qtySold = new javax.swing.JLabel();
        lbl_index1 = new javax.swing.JLabel();
        lbl_index2 = new javax.swing.JLabel();
        lbl_index3 = new javax.swing.JLabel();
        lbl_index4 = new javax.swing.JLabel();
        lbl_index5 = new javax.swing.JLabel();
        Report_lbl_pid1 = new javax.swing.JLabel();
        Report_lbl_pid2 = new javax.swing.JLabel();
        Report_lbl_pid3 = new javax.swing.JLabel();
        Report_lbl_pid4 = new javax.swing.JLabel();
        Report_lbl_pid5 = new javax.swing.JLabel();
        Report_lbl_qty1 = new javax.swing.JLabel();
        Report_lbl_qty2 = new javax.swing.JLabel();
        Report_lbl_qty3 = new javax.swing.JLabel();
        Report_lbl_qty4 = new javax.swing.JLabel();
        Report_lbl_qty5 = new javax.swing.JLabel();
        base_lbl_tearHere = new javax.swing.JLabel();
        base_lbl_separator = new javax.swing.JLabel();
        Report_lbl_PName1 = new javax.swing.JLabel();
        Report_lbl_PName2 = new javax.swing.JLabel();
        Report_lbl_PName3 = new javax.swing.JLabel();
        Report_lbl_PName4 = new javax.swing.JLabel();
        Report_lbl_PName5 = new javax.swing.JLabel();
        lbl_plantName = new javax.swing.JLabel();
        base_btn_printReceipt = new keeptoo.KButton();
        jLabel4 = new javax.swing.JLabel();
        top_lbl_close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportPanel.setBackground(new java.awt.Color(255, 255, 255));
        reportPanel.setPreferredSize(new java.awt.Dimension(598, 350));
        reportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_lbl_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        base_lbl_title.setText("Plant Nursery");
        reportPanel.add(base_lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 220, -1));

        base_lbl_subheading.setText("A greener step towards you");
        reportPanel.add(base_lbl_subheading, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 170, -1));

        base_lbl_emoticon.setText("    (✿◠‿◠)       (✿◠‿◠)       (✿◠‿◠)       (✿◠‿◠)       (✿◠‿◠)       (✿◠‿◠)       (✿◠‿◠)       (✿◠‿◠)       (✿◠‿◠)       ");
        reportPanel.add(base_lbl_emoticon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, -1, -1));

        base_lbl_Date.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(base_lbl_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 95, 80, 10));

        base_logoPanel.setBackground(new java.awt.Color(255, 255, 255));
        base_logoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_logoPanel_lbl_flowerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/45x41 red flower zoom.png"))); // NOI18N
        base_logoPanel_lbl_flowerImage.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        base_logoPanel.add(base_logoPanel_lbl_flowerImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        reportPanel.add(base_logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        lbl_address1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lbl_address1.setText("Address 1");
        reportPanel.add(lbl_address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 5, -1, -1));

        lbl_address2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lbl_address2.setText("Address 2");
        reportPanel.add(lbl_address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        lbl_address3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lbl_address3.setText("Address 3");
        reportPanel.add(lbl_address3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 35, -1, -1));

        lbl_dateSpanning.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lbl_dateSpanning.setText("Data spanning");
        reportPanel.add(lbl_dateSpanning, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lbl_dateFrom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_dateFrom.setText("From : ");
        reportPanel.add(lbl_dateFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbl_dateTo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_dateTo.setText("To : ");
        reportPanel.add(lbl_dateTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Report_lbl_fromDate.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 430, -1));

        Report_lbl_toDate.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 430, -1));

        Report_lbl_action.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Report_lbl_action.setText("Data spanning");
        reportPanel.add(Report_lbl_action, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        lbl_PID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_PID.setText("PID");
        reportPanel.add(lbl_PID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lbl_qtySold.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_qtySold.setText("Quantity sold");
        reportPanel.add(lbl_qtySold, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        lbl_index1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lbl_index1.setText("1)");
        reportPanel.add(lbl_index1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 10, -1));

        lbl_index2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lbl_index2.setText("2)");
        reportPanel.add(lbl_index2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 10, -1));

        lbl_index3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lbl_index3.setText("3)");
        reportPanel.add(lbl_index3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 10, -1));

        lbl_index4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lbl_index4.setText("4)");
        reportPanel.add(lbl_index4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 10, -1));

        lbl_index5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        lbl_index5.setText("5)");
        reportPanel.add(lbl_index5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 10, -1));

        Report_lbl_pid1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_pid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 70, -1));

        Report_lbl_pid2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_pid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 70, -1));

        Report_lbl_pid3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_pid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 70, -1));

        Report_lbl_pid4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_pid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 70, -1));

        Report_lbl_pid5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_pid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 70, -1));

        Report_lbl_qty1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_qty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 70, -1));

        Report_lbl_qty2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_qty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 70, -1));

        Report_lbl_qty3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_qty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 70, -1));

        Report_lbl_qty4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_qty4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 70, -1));

        Report_lbl_qty5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_qty5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 70, -1));

        base_lbl_tearHere.setText(" -  -  -✂ -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -");
        reportPanel.add(base_lbl_tearHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        base_lbl_separator.setText("-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - ");
        reportPanel.add(base_lbl_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 140, -1, -1));

        Report_lbl_PName1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_PName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 300, -1));

        Report_lbl_PName2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_PName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 300, -1));

        Report_lbl_PName3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_PName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 300, -1));

        Report_lbl_PName4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_PName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 300, -1));

        Report_lbl_PName5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        reportPanel.add(Report_lbl_PName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 300, -1));

        lbl_plantName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_plantName.setText("Plant Name");
        reportPanel.add(lbl_plantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jScrollPane1.setViewportView(reportPanel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 570, 370));

        base_btn_printReceipt.setText("Print Receipt");
        base_btn_printReceipt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        base_btn_printReceipt.setkBorderRadius(30);
        base_btn_printReceipt.setkEndColor(new java.awt.Color(0, 0, 204));
        base_btn_printReceipt.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        base_btn_printReceipt.setkHoverStartColor(new java.awt.Color(153, 255, 153));
        base_btn_printReceipt.setkPressedColor(new java.awt.Color(255, 255, 51));
        base_btn_printReceipt.setkSelectedColor(new java.awt.Color(255, 255, 51));
        base_btn_printReceipt.setkStartColor(new java.awt.Color(0, 204, 204));
        base_btn_printReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base_btn_printReceiptActionPerformed(evt);
            }
        });
        getContentPane().add(base_btn_printReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));

        jLabel4.setText("🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 590, -1));

        top_lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/close-window-45 (2).png"))); // NOI18N
        top_lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                top_lbl_closeMouseClicked(evt);
            }
        });
        getContentPane().add(top_lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background/blossoms rainfall.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void base_btn_printReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base_btn_printReceiptActionPerformed
        try{
            printComponent(reportPanel);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_base_btn_printReceiptActionPerformed

    private void top_lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_top_lbl_closeMouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Would you like to close the print frame?");
        if(result==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_top_lbl_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportPrinter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportPrinter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportPrinter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportPrinter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*
                (String action, String from, String to, String a1, String a2, String a3, String a4, String a5, 
            String b1, String b2, String b3, String b4, String b5)
                */
                String action = null;
                String from = null;
                String to = null;
                String a1 = null;
                String a2 = null;
                String a3 = null;
                String a4 = null;
                String a5 = null;
                String b1 = null;
                String b2 = null;
                String b3 = null;
                String b4 = null;
                String b5 = null;
                String p1 = null;
                String p2 = null;
                String p3 = null;
                String p4 = null;
                String p5 = null;
                new ReportPrinter(action,from,to,a1,a2,a3,a4,a5,b1,b2,b3,b4,b5,p1,p2,p3,p4,p5).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Report_lbl_PName1;
    private javax.swing.JLabel Report_lbl_PName2;
    private javax.swing.JLabel Report_lbl_PName3;
    private javax.swing.JLabel Report_lbl_PName4;
    private javax.swing.JLabel Report_lbl_PName5;
    private javax.swing.JLabel Report_lbl_action;
    private javax.swing.JLabel Report_lbl_fromDate;
    private javax.swing.JLabel Report_lbl_pid1;
    private javax.swing.JLabel Report_lbl_pid2;
    private javax.swing.JLabel Report_lbl_pid3;
    private javax.swing.JLabel Report_lbl_pid4;
    private javax.swing.JLabel Report_lbl_pid5;
    private javax.swing.JLabel Report_lbl_qty1;
    private javax.swing.JLabel Report_lbl_qty2;
    private javax.swing.JLabel Report_lbl_qty3;
    private javax.swing.JLabel Report_lbl_qty4;
    private javax.swing.JLabel Report_lbl_qty5;
    private javax.swing.JLabel Report_lbl_toDate;
    private keeptoo.KButton base_btn_printReceipt;
    private javax.swing.JLabel base_lbl_Date;
    private javax.swing.JLabel base_lbl_emoticon;
    private javax.swing.JLabel base_lbl_separator;
    private javax.swing.JLabel base_lbl_subheading;
    private javax.swing.JLabel base_lbl_tearHere;
    private javax.swing.JLabel base_lbl_title;
    private javax.swing.JPanel base_logoPanel;
    private javax.swing.JLabel base_logoPanel_lbl_flowerImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_PID;
    private javax.swing.JLabel lbl_address1;
    private javax.swing.JLabel lbl_address2;
    private javax.swing.JLabel lbl_address3;
    private javax.swing.JLabel lbl_dateFrom;
    private javax.swing.JLabel lbl_dateSpanning;
    private javax.swing.JLabel lbl_dateTo;
    private javax.swing.JLabel lbl_index1;
    private javax.swing.JLabel lbl_index2;
    private javax.swing.JLabel lbl_index3;
    private javax.swing.JLabel lbl_index4;
    private javax.swing.JLabel lbl_index5;
    private javax.swing.JLabel lbl_plantName;
    private javax.swing.JLabel lbl_qtySold;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JLabel top_lbl_close;
    // End of variables declaration//GEN-END:variables
}
